CREATE TABLE lCampo (codRegistro VARCHAR(12) PRIMARY KEY, nombre TEXT NOT NULL, descripcion TEXT NOT NULL, tipo TEXT NOT NULL, unidad TEXT NOT NULL, enlace TEXT NOT NULL,
borrado VARCHAR(1) NOT NULL, 
FOREIGN KEY (codRegistro) REFERENCES general(codGeneral) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;